### ISSUE TITLE
Clicking revert also clears the filter type.

### ISSUE THREAD

**Issue by rishibhatia5354** [tableau/extension-filter-bookmarks#19]
Have a filter which is set to - "Multiple Values - Custom List" - everytime i revert the filter, it changes the type of filter to "Multiple Values - List"

**Comment by KeshiaRose** [comment]
Hi @rishibhatia5354, unfortunately, this is a limitation of the API so I can't change that behavior. Could you please open this issue in the extensions-api repo: https://github.com/tableau/extensions-api
-Keshia
