### ISSUE TITLE
Do you access data if we add this extension to the tableau dashboard?

### ISSUE THREAD

**Issue by utkarsha-bhamare** [tableau/extension-filter-bookmarks#33]
I wanted to understand data access mechanism used by this tableau extension.
Do you access dashboard data? If yes, please explain your data access strategy.

**Comment by KeshiaRose** [comment]
Hi @utkarsha-bhamare, great question! All operations for this extension, including the ones that access/use dashboard data, happen locally on your machine. Once the scripts are loaded everything runs in the client, no data is transmitted elsewhere. 
-Keshia

**Comment by utkarsha-bhamare** [comment]
Thanks for the answer. I have a one more question. This extension clears all the filters, but does not unselect the bar/mark selected on the bar chart.

Is there any way to clear bar chart selection?

**Comment by KeshiaRose** [comment]
Hmm no there isn't any way right now to clear selection but that is a good idea for the future!
