### ISSUE TITLE
Is there any way to clear bar chart selection?

### ISSUE THREAD

**Issue by utkarsha-bhamare** [tableau/extension-filter-bookmarks#34]
This extension clears all the filters, but does not unselect the bar/mark selected on the bar chart.

Is there any way to clear bar chart selection?

**Comment by KeshiaRose** [comment]
Thanks for the idea @utkarsha-bhamare I've marked this as a feature request and hope to add it in the future!

**Comment by bcantoni** [comment]
Cleanup: closing old feature requests which we won't be able to do.
