### ISSUE TITLE
Action Filters also reverted

### ISSUE THREAD

**Issue by HariNSri** [tableau/extension-filter-bookmarks#4]
Hi

Opened the configuration window and clicked on "Save Settings".

When we click on revert filter, dashboard worksheets filters are reverted, but the Action Filters between worksheets are changing to 'Show all values' filter.

![image](https://user-images.githubusercontent.com/49035968/65708574-814fd400-e0ac-11e9-8ac7-0ee97c6d259a.png)

**Comment by KeshiaRose** [comment]
Hi @HariNSri,

Sorry for the delayed response. Could you send me a sample workbook showing what you're seeing? I'm unable to reproduce it on my own.

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Closing due to no response, please feel free to re-open this ticket!
