### ISSUE TITLE
Resetting Only a few filters on a Sheet

### ISSUE THREAD

**Issue by Sanjay500-500** [tableau/extension-filter-bookmarks#45]
Hi is there any way to only reset a few filters on a sheet? 

Thanks.

**Comment by KeshiaRose** [comment]
Hi @Sanjay500-500, no not currently but I'll consider this when I make updates in the future!

**Comment by Sanjay500-500** [comment]
Great, thank you so much.

**Comment by bcantoni** [comment]
Cleanup: closing old feature requests which we won't be able to do.
