### ISSUE TITLE
Conflict with floating containers with non-standard icon in show/hide button

### ISSUE THREAD

**Issue by TimB1023** [tableau/extension-filter-bookmarks#6]
Hi Keshia,

The extension has been working great for a while now, but suddenly had problems yesterday I think I've narrowed it down to using floating containers that I show/hide using a button. It appears to be OK until I change from the standard burger button / X button combination.

Once I have configured the buttons with alternatives (image or unicode symbols), clicking on the extension results in a short pause, then Tableau shuts down. I'd be happy to send you log files if you think it would help.

I'm running desktop 2019.3

Thank you!
Tim

**Comment by TimB1023** [comment]
This issue seems to have been resolved with the latest Tableau update (2019.4)

**Comment by KeshiaRose** [comment]
Glad to hear it @TimB1023!
