### ISSUE TITLE
What about context or viz filters, and top n sets?

### ISSUE THREAD

**Issue by thomassie** [tableau/extension-filter-bookmarks#7]
Hey guys,

I was really looking forward to using your filter bookmarks extension. However, I can't use it as it works only for 'standard' filters. Like, if you have a couple of drop-down filters it works well. However, I want to create bookmarks in a more advanced dashboard that uses bar charts and a top n table. If I'm applying your extension here it creates a mess. Sorry!

Am I missing anything here?

Thanks for a quick reply,

Thomas

**Comment by KeshiaRose** [comment]
Hi @thomassie,

As of right now we are only able to reset "standard" filters but we may add more functionality to the API in the future, I hope you can find a workaround!

Take care,
Keshia

**Comment by thomassie** [comment]
Hey Keshia,

well, when publishing a dashboard to the server I can at least there use bookmarks/screenshots.
However, conditional annotations would be the coolest thing I'd wish for the right now...!  ;)

Thanks a lot!
