### ISSUE TITLE
Feature request: Ability to use image instead of text for button?

### ISSUE THREAD

**Issue by mac471** [tableau/extension-filter-bookmarks#9]
This is a great extension -  we use it often.  However, we need to deploy in multiple languages so localization of our workbooks requires an extra step of editing this extension for every language we support. 

If we could use an image for the button, that would allow us to take the language-specific element out of this extension.

Another workaround we've tried is using a character-based symbol, like this:
![image](https://user-images.githubusercontent.com/17917026/76674047-9a2c4300-6581-11ea-95e9-b7a434e4b802.png)

except that there is no way to change the font size of the label to make it more readable.

Any ideas?

Thanks.

**Comment by KeshiaRose** [comment]
Thanks for the idea @mac471! When you tried using the symbols, was it too small?

Take care,
Keshia

**Comment by mac471** [comment]
Yes, it was too small to read.  It would be great to be able to use an image. UX could be similar to the Navigation/Edit Button dialog where you can specify either text or an image.

This would really help with localization.

Any chance that this could be implemented?

Thanks.

**Comment by KeshiaRose** [comment]
Just added it, reload!

**Comment by mac471** [comment]
WOW. Thanks for doing this so quickly.  Very much appreciated!

You made my day!

**Comment by mac471** [comment]
This is a great feature - thanks for implementing it. I am trying to use icons instead of text to help with localization (e.g. English/French for Canadian applications).

One question - when the extension first loads, you always see the default text "Revert Filters". Is this something that can be changed so that it doesn't show this before showing either the user-specified label text or the user-specified image?   If this is a restriction on how extensions work, how about just showing nothing (or an ellipsis) in the space instead of "Revert Filters".

A couple of users have commented on this, especially the non-English speaking ones.

**Comment by KeshiaRose** [comment]
Just made the update to show nothing while the settings are being fetched!

**Comment by mac471** [comment]
Hi Keshia - this is great - thanks for making this change!
